# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u9662\u7cfb')),
                ('image', models.ImageField(upload_to='school/%Y/%m', verbose_name='\u7167\u7247')),
                ('desc', models.TextField(verbose_name='\u4ecb\u7ecd')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('course_nums', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
            ],
            options={
                'verbose_name': '\u9662\u7cfb',
                'verbose_name_plural': '\u9662\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=9, verbose_name='\u5b66\u53f7')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='\u6635\u79f0')),
                ('image', models.ImageField(default='student/default.png', upload_to='student/%Y/%m', verbose_name='\u7167\u7247')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6, verbose_name='\u6027\u522b')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='\u9662\u7cfb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=6, verbose_name='\u6559\u5e08\u53f7')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d')),
                ('image', models.ImageField(default='teacher/default.png', upload_to='teacher/%Y/%m', verbose_name='\u7167\u7247')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(default=18, verbose_name='\u5e74\u9f84')),
                ('start', models.DateField(verbose_name='\u53c2\u52a0\u5de5\u4f5c\u65f6\u95f4')),
                ('title', models.CharField(max_length=20, verbose_name='\u6559\u5e08\u804c\u79f0')),
                ('detail', models.TextField(verbose_name='\u66f4\u591a\u4ecb\u7ecd')),
                ('points', models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='\u9662\u7cfb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08',
            },
        ),
    ]
